Path = "/home/qmiao/go/src/github.com/cdutwhu/n3-frontend-test/config/cfg-clt-sif2json.toml"
LogFile = "./go-client-[DATE].log"
ServiceName = "N3-SIF2JSON"

[Server]
  Protocol = "http"
  IP = "192.168.31.168"
  Port = 1324

[Access]
  Timeout = 3

[Route]
  HELP = "/"
  SIF2JSON = "/sif2json/v0.2.1"
  JSON2SIF = "/json2sif/v0.2.1"
